In [1]:
import numpy as np
import pandas as pd

from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1 = Series([1,2,3],index=list('TUV'))
ser2 = Series([3,4],index=list('XY'))

In [7]:
ser1

T    1
U    2
V    3
dtype: int64

In [8]:
ser2

X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2])

T    1
U    2
V    3
X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2],axis=1)

0    1
T  1.0  NaN
U  2.0  NaN
V  3.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [11]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    1
      U    2
      V    3
cat2  X    3
      Y    4
dtype: int64

In [13]:
dframe1 = DataFrame(np.random.randn(4,3),columns=list('XYZ'))
dframe2 = DataFrame(np.random.randn(3,3),columns=list('YQX'))

In [14]:
dframe1

X         Y         Z
0 -2.484880  1.330581 -0.114625
1  0.349678  0.779239 -0.073768
2  0.213636 -0.307349  0.391095
3 -0.638599 -2.071420 -0.242317

In [15]:
dframe2

Y         Q         X
0 -1.309606  1.547105  2.582298
1 -1.340432 -0.025957 -1.260150
2 -1.287813  0.016564 -0.645365

In [16]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN -2.484880  1.330581 -0.114625
1       NaN  0.349678  0.779239 -0.073768
2       NaN  0.213636 -0.307349  0.391095
3       NaN -0.638599 -2.071420 -0.242317
0  1.547105  2.582298 -1.309606       NaN
1 -0.025957 -1.260150 -1.340432       NaN
2  0.016564 -0.645365 -1.287813       NaN

In [17]:
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN -2.484880  1.330581 -0.114625
1       NaN  0.349678  0.779239 -0.073768
2       NaN  0.213636 -0.307349  0.391095
3       NaN -0.638599 -2.071420 -0.242317
4  1.547105  2.582298 -1.309606       NaN
5 -0.025957 -1.260150 -1.340432       NaN
6  0.016564 -0.645365 -1.287813       NaN