In [1]:
import numpy as np

In [4]:
my_list1 = [1,2,3,4]

In [7]:
my_array1 = np.array(my_list1)

In [8]:
my_array1

array([1, 2, 3, 4])

In [14]:
my_list2 = [11,22,33,44]

In [15]:
my_lists=[my_list1,my_list2]

In [16]:
my_array2 = np.array(my_lists)

In [17]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [18]:
my_array2.shape

(2L, 4L)

In [19]:
my_array2.dtype

dtype('int32')

In [20]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [21]:
my_zeros_array = np.zeros(5)

In [22]:
my_zeros_array.dtype

dtype('float64')

In [23]:
np.ones([5,5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [26]:
help(np.ones)

Help on function ones in module numpy.core.numeric:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    zeros, ones_like
    
    Examples
    --------
    >>> np.ones(5)
    array([ 1.,  1.,  1.,  1.,  1.])
    
    >>> np.ones((5,), dtype=np.int)
    array([1, 1, 1, 1, 1])
    
    >>> np.ones((2, 1))
    array([[ 1.],
           [ 1.]])
    
    >>> s = (2,2)
    >>> np.ones(s)
   

In [27]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [28]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [29]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [30]:
my_zeros_array = np.zeros(5)

In [31]:
my_zeros_array.dtype

dtype('float64')

In [32]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [33]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])