In [1]:
import numpy as np

In [3]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

universal functions can work on all arrays

In [6]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [7]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [8]:
A = np.random.randn(10)
A

array([ 1.15943221, -2.68050464, -1.13610897, -0.38058635, -0.26369675,
       -0.65002637,  0.94095556,  0.57052759,  0.30324688, -0.80662598])

In [10]:
B =np.random.randn(10)
B

array([-0.54167432, -0.30251698,  0.98662383, -2.16020395, -0.20430956,
       -1.95471923,  0.44807317, -0.49215948, -0.81204687, -0.49774125])

Binary Function

In [11]:
np.add(A,B)

array([ 0.61775789, -2.98302163, -0.14948514, -2.54079031, -0.46800631,
       -2.6047456 ,  1.38902873,  0.07836811, -0.50879999, -1.30436724])

In [12]:
np.maximum(A,B)

array([ 1.15943221, -0.30251698,  0.98662383, -0.38058635, -0.20430956,
       -0.65002637,  0.94095556,  0.57052759,  0.30324688, -0.49774125])

In [14]:

website = 'https://docs.scipy.org/doc/numpy/reference/ufuncs.html'
import webbrowser
webbrowser.open(website)

True